---
- name: Clone test-network-function
  git:
    repo: "{{ test_network_function_repo }}"
    version: "{{ test_network_function_version }}"
    dest: "{{ tnf_git_dir }}/test_network_function"
    force: yes
  # On RHEL8 git clone can sporadically fail with OpenSSL SSL_read:
  # SSL_ERROR_SYSCALL, errno 104. This is a workaround to try cloning the repo
  # multiple times.
  retries: 3
  delay: 10

- name: Clone cnf-certification-test-partner
  git:
    repo: "{{ cnf_certification_test_partner_repo }}"
    version: "{{ cnf_certification_test_partner_version }}"
    dest: "{{ tnf_git_dir }}/cnf_certification_test_partner"
    force: yes
  # On RHEL8 git clone can sporadically fail with OpenSSL SSL_read:
  # SSL_ERROR_SYSCALL, errno 104. This is a workaround to try cloning the repo
  # multiple times.
  retries: 3
  delay: 10

- name: Build the partner pod
  shell: |
    set -e
    cd {{ tnf_git_dir }}/cnf_certification_test_partner
    podman build -t testnetworkfunction/cnf-test-partner .
    cd test-partner
    oc create -f ./namespace.yaml
    oc create -f ./partner.yaml

...
