---
# Step 0 : initial step
- name: "Execute initial step"
  hosts: jumphost
  gather_facts: False
  tags:
    - job
  tasks:
    - name: Read credentials from env vars
      set_fact:
        dci_client_id="{{ lookup('env','DCI_CLIENT_ID') }}"
        dci_api_secret="{{ lookup('env','DCI_API_SECRET') }}"
        dci_cs_url="{{ lookup('env','DCI_CS_URL') }}"
      no_log: true

    # Schedule a new job only if not passed via pipeline
    - name: "Schedule a new job"
      dci_job:
        components: "{{ dci_components }}"
        topic: "{{ dci_topic }}"
      register: job_info
      when: job_info is not defined

    - name: set job id
      set_fact:
        job_id: "{{ job_info.job.id }}"

    - name: set job state
      dci_job:
        id: "{{ job_id }}"
        status: "new"

    - name: 'Set DCI tags for the current job'
      dci_job:
        id: '{{ job_id }}'
        tags: '{{ dci_tags }}'
      when: dci_tags[0] is defined

# Step 1 : "pre-run" step
- name: "Execute pre-run step"
  hosts: jumphost
  tags:
    - pre-run
  tasks:
    - block:
        - name: Run the pre-run hook
          include_tasks: 'plays/pre-run.yml'

        - name: Run the pre-run hook
          include_tasks: '{{ item }}/hooks/pre-run.yml'
          loop: "{{ dci_config_dirs }}"
          when:
            - "'{{ item }}/hooks/pre-run.yml' in hooks_found"

      rescue: &error_with_upload_logs
        - name: "Execute the error process"
          include_tasks: plays/error.yml

# Step 2 : "running" step
- name: "Execute install step"
  hosts: jumphost
  tags:
    - running
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - block:
        - name: running
          dci_job:
            id: "{{ job_id }}"
            status: "running"

        - name: "Execute install"
          include_tasks: "{{ item }}/hooks/install.yml"
          loop: "{{ dci_config_dirs }}"
          when:
            - "'{{ item }}/hooks/install.yml' in hooks_found"

      rescue: &failure_with_upload_logs
        - name: "Execute the failure process"
          include_tasks: plays/failure.yml

# Step 3 : "tests" step
- name: "Execute tests step"
  hosts: jumphost
  tags:
    - testing
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - block:
        - name: "Execute Red Hat tests"
          include_tasks: plays/tests.yml

        - name: "Execute partner tests"
          include_tasks: "{{ item }}/hooks/tests.yml"
          loop: "{{ dci_config_dirs }}"
          when:
            - "'{{ item }}/hooks/tests.yml' in hooks_found"
      rescue: *failure_with_upload_logs

# Step 4 : "post-run" step
- name: "Execute post-run step"
  hosts: jumphost
  tags:
    - post-run
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - block:
        - name: "Run post-run"
          include_tasks: plays/post-run.yml
