#!/bin/bash

start=0
params="$(getopt -o hsc: -l help,start: --name "$(basename -- "$0")" -- "$@")"

function usage ()
{
    name=$(basename -- "$0")
    cat << EOF
Usage: $name [-h] [-s] [-c CONFIG] -- [ansible-playbook args]

arguments:
    -h, --help        Display this help message.
    -s, --start       Start the dci-openshift-agent.

EOF
    exit 0
}

eval set -- "$params"
unset params

while true
do
    case $1 in
        -h|--help)
            usage
            ;;
        -s|--start)
            start=1
            shift
          ;;
        -c|--config)
            shift
            config=$1
            shift
            ;;
        --)
            shift
            ansible_args=$@
            break
            ;;
        *)
            usage
            ;;
    esac
done

if [ $( id -u dci-openshift-app-agent ) -ne $( id -u ) ]; then
  echo "must be run as the dci-openshift-app-agent user"
  usage
fi

if [ "$start" -eq 1 ]; then
    [ -e /etc/dci-openshift-app-agent/dcirc.sh ] && . /etc/dci-openshift-app-agent/dcirc.sh
    [ -d /usr/share/dci-openshift-app-agent ] && cd /usr/share/dci-openshift-app-agent
    RANDOM_UUID=`uuidgen`
    ANSIBLE_LOG_PATH=/var/tmp/ansible.${RANDOM_UUID}.log
    ansible-playbook dci-openshift-app-agent.yml -e @$config $ansible_args
else
    usage
fi
