apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: performance
spec:
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  cpu:
    isolated: "2-3"
    reserved: "0-1"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 4
      node: 0
  realTimeKernel:
    enabled: true
  numa:
    topologyPolicy: "best-effort"

