---

- name: Assert the required variables are defined
  ansible.builtin.assert:
    that:
      - spoke_cluster_kubeconfig_path is defined
      - spoke_cluster_kubeconfig_path | length > 0
      - spoke_cluster_name is defined
      - spoke_cluster_name | length > 0

...
