---

- name: Create components for already deployed Kubernetes resources
  ansible.builtin.include_role:
    name: redhatci.ocp.resources_to_components
  when: rtc_resources_to_components | length

...
