---

- name: Post-run
  dci_job:
    id: "{{ job_id }}"
    status: "post-run"
  delegate_to: localhost
  tags: [dci]

# Only do this if `outputs` variable is not defined, to allow customizing
# this variable.
# By default, we provide the kubeconfig as standard output.
- name: Set outputs to be copied
  ansible.builtin.set_fact:
    outputs:
      kubeconfig: "{{ kubeconfig_path }}"
  when: outputs is not defined

# Only copy each entry from `outputs` pipeline folder if:
# - `outputs` folder (represented by `job_info.outputs` variable) is defined in the pipeline
# - `outputs` local variable contains the entry defined in `outputs` pipeline field
# This is to avoid making a job to fail because of a wrong outputs configuration.
- name: Copy outputs if defined
  when:
    - job_info.outputs is defined
    - job_info.outputs != None
    - outputs[item.key] is defined
  block:
    - name: Create outputs directory
      ansible.builtin.file:
        path: "{{ item.value | dirname }}"
        state: directory
        recurse: true
      loop: "{{ job_info.outputs | dict2items }}"
    - name: Copy outputs in Jumphost
      ansible.builtin.copy:
        src: "{{ outputs[item.key] }}"
        dest: "{{ item.value }}"
        mode: "0644"
      loop: "{{ job_info.outputs | dict2items }}"
    - name: Copy outputs in localhost
      ansible.builtin.copy:
        src: "{{ outputs[item.key] }}"
        dest: "{{ item.value }}"
        mode: "0644"
      loop: "{{ job_info.outputs | dict2items }}"
      delegate_to: localhost

- name: Get the differences from the previous DCI job
  ansible.builtin.shell: "dci-diff-jobs --job_id_1 {{ job_id }} > {{ job_logs.path }}/diff-jobs.txt"
  delegate_to: localhost
  ignore_errors: true

...
