---

- name: Post-run play
  delegate_to: localhost
  delegate_facts: true
  block:
    - name: Post-run state
      dci_job:
        id: "{{ job_id }}"
        status: "post-run"
      tags: [dci]

    # outputs is passed by dci-pipeline in the job_info variable
    # it is a dictionary like this:
    # <var name>: <path of the file to save the content>
    - name: Print job outputs location
      when:
        - job_info.outputs is defined
      ansible.builtin.debug:
        msg: "{{ job_info['outputs'] }}"

    - name: Backward compatibility kubeconfig variable
      when:
        - kubeconfig is not defined
        - kubeconfig_path is defined
      ansible.builtin.set_fact:
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Copy outputs if defined
      when:
        - job_info.outputs is defined
        - job_info.outputs != None
      ansible.builtin.copy:
        src: "{{ hostvars['localhost'][item.key] }}"
        dest: "{{ item.value }}"
        mode: "0644"
      loop: "{{ job_info.outputs | dict2items }}"

    - name: Get the differences from the previous DCI job
      ansible.builtin.shell: "dci-diff-jobs --job_id_1 {{ job_id }} > {{ job_logs.path }}/diff-jobs.txt"
      ignore_errors: true

- name: Save job info in the cluster
  when: dci_cluster_metadata | default(true) | bool
  block:
    - name: Create DCI namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-dci
      register: dci_ns
      ignore_errors: true

    - name: Create DCI configmap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: "doaa-{{ ansible_date_time.epoch }}"
            namespace: openshift-dci
          data:
            job_info: "{{ job_info | redhatci.ocp.redact | to_json }}"
      when: dci_ns is succeeded
...
