---
- name: Set facts for pull secrets
  ansible.builtin.set_fact:
    dci_pullsecrets: "{{ job_info.job.topic.data.pull_secret | default({}) }}"
    pullsecret_tmp_file: "/tmp/ps_{{ job_id | default(lookup('password', '/dev/null length=8')) }}.json"
  no_log: true

- name: Read partner creds
  ansible.builtin.set_fact:
    partner_pullsecrets: "{{ lookup('file', partner_creds) | from_json }}"
  when: partner_creds | length
  no_log: true

- name: Merge pullsecrets found
  ansible.builtin.set_fact:
    pullsecrets: "{{ dci_pullsecrets | combine(partner_pullsecrets | default({}), recursive=True) }}"
  no_log: true

- name: Create unique pullsecret (in reverse order)
  ansible.builtin.copy:
    dest: "{{ pullsecret_tmp_file }}"
    content: |
      {
        "auths": {
        {% for repo in pullsecrets.auths | sort(reverse=True) | list %}
          "{{ repo }}": {{ pullsecrets.auths[repo] | to_json }}{% if loop.last %}{% else %},{% endif %}
        {% endfor %}
        }
      }
    mode: '0644'
  no_log: true
