---
- name: Helm Chart Certification Project
  ansible.builtin.include_role:
    name: redhatci.ocp.create_helmchart
  vars:
    product_type: "helmchart"
  when: helmchart_to_certify is defined

- name: "Chart verifier tests"
  ansible.builtin.include_role:
    name: redhatci.ocp.chart_verifier
  when:
    - do_chart_verifier|bool

- name: "Pause after chart_verifier"
  ansible.builtin.pause:
    minutes: "{{ chart_verifier_wait }}"
  when:
    - chart_verifier_wait|int > 0

- name: CNF Project Creation-Only tests for Vendor Validation
  include_role:
    name: redhatci.ocp.openshift_cnf
  vars:
    product_type: "openshift_cnf"
  when: cnf_to_certify is defined

- name: Set KBPC CWE Project ID from CNF Certification Project
  ansible.builtin.set_fact:
    kbpc_cwe_project_id: "{{ cert_project_id }}"
  when:
    - cnf_to_certify is defined
    - cert_project_id | length > 0

- name: Run k8s_best_practices_certsuite tests
  ansible.builtin.include_role:
    name: redhatci.ocp.k8s_best_practices_certsuite
  vars:
    kbpc_kubeconfig: "{{ kubeconfig_path }}"
    kbpc_log_path: "{{ job_logs.path }}"
    kbpc_pullsecret: "{{ pullsecret_tmp_file | default('') }}"
    kbpc_registry: "{{ dci_local_registry }}"
    kbpc_partner_creds: "{{ partner_creds }}"
    kbpc_image_suffix: "{{ job_id }}"
  when: do_certsuite|bool

- name: "Pause after certsuite"
  ansible.builtin.pause:
    minutes: "{{ certsuite_wait }}"
  when:
    - certsuite_wait|int > 0

- name: Preflight container-only tests
  vars:
    preflight_dci_all_components_are_ga: "{{ dci_all_components_are_ga }}"
  ansible.builtin.include_role:
    name: redhatci.ocp.preflight
    tasks_from: main_standalone_containers_certification
  when: preflight_containers_to_certify is defined

- name: Operator-SDK Scorecard tests
  vars:
    scorecard_oc_tool_path: "{{ oc_tool_path }}"
    scorecard_partner_creds: "{{ partner_creds }}"
    scorecard_kubeconfig_path: "{{ kubeconfig_path }}"
    scorecard_pullsecret_tmp_file: "{{ pullsecret_tmp_file | default('') }}"
    scorecard_job_logs: "{{ job_logs }}"
    scorecard_dci_local_registry: "{{ dci_local_registry }}"
    scorecard_dci_disconnected: "{{ dci_disconnected }}"
  ansible.builtin.include_role:
    name: redhatci.ocp.operator_sdk
  when: scorecard_operators is defined

- name: Compute removed API after executing the workload
  ansible.builtin.include_role:
    name: redhatci.ocp.deprecated_api
    apply:
      delegate_to: localhost
  vars:
    deprecated_api_logs:
      path: "{{ job_logs.path }}"
  when: check_workload_api | default(true) | bool

- name: Preflight check operator tests
  vars:
    preflight_dci_all_components_are_ga: "{{ dci_all_components_are_ga }}"
  ansible.builtin.include_role:
    name: redhatci.ocp.preflight
  when: preflight_operators_to_certify is defined

- name: Get final job info
  dci_job:
    id: "{{ job_id }}"
  register: job_info_updated
  delegate_to: localhost

- name: Test_ if the OCP component is present
  assert:
    success_msg: "{{ ocp_component_id }} is present"
    fail_msg: "{{ ocp_component_id }} is absent"
    that:
      - (job_info_updated['job']['components'] | selectattr('id', 'equalto', ocp_component_id) | list | length) > 0
  ignore_errors: true
...
